version: '3.1'

services:
  db-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: learnNodejs
      MYSQL_ROOT_PASSWORD: example
    ports: 
      - 3307:3306
  redis:
    image: redis:alpine
    ports: 
      - 6379:6379
    volumes:
      - redis-data:/data
volumes:
  redis-data: